version: '3.4'

services:
  scallybot:
    container_name: scallybot
    image: scallybot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/logs/
    env_file: .env